/* CHEAT Gamble Hub backend
 * Node 18+ / Express / better-sqlite3
 * This is the authoritative side: balances, RNG, XP, cooldowns and cashouts never trust the browser.
 */
const express=require('express');
const crypto=require('crypto');
const Database=require('better-sqlite3');
const path=require('path');
const fs=require('fs');
const app=express();
const db=new Database(process.env.GAMBLE_DB||path.join(__dirname,'gamble.sqlite'));
db.pragma('journal_mode = WAL');
const schemaPath=path.join(__dirname,'schema.sql');
if(fs.existsSync(schemaPath)) db.exec(fs.readFileSync(schemaPath,'utf8'));
const now=()=>Math.floor(Date.now()/1000);
const PORT=Number(process.env.PORT||3000);
const SESSION_COOKIE='cheat_gamble_sid';
const sessions=new Map();
const REQUIRED_ROLE_ID=process.env.DISCORD_REQUIRED_ROLE_ID||'';
const DISCORD_BOT_TOKEN=process.env.DISCORD_BOT_TOKEN||'';
const DISCORD_GUILD_ID=process.env.DISCORD_GUILD_ID||'';
const GTPS_SECRET=process.env.GTPS_SECRET||'CHANGE_ME';
const GTPS_BRIDGE_SECRET=process.env.GTPS_BRIDGE_SECRET||'CHANGE_ME';
app.use(express.json({limit:'16kb'}));
app.use((req,res,next)=>{res.setHeader('Cache-Control','no-store');next()});
function sign(s){return crypto.createHmac('sha256',GTPS_SECRET).update(s).digest('hex')}
function issueSession(accountId){const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{accountId,expires:Date.now()+7*864e5});return sid}
function auth(req,res,next){const sid=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(SESSION_COOKIE+'='))?.split('=')[1];const s=sid&&sessions.get(sid);if(!s||s.expires<Date.now())return res.status(401).json({error:'Not linked'});req.account=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(s.accountId);if(!req.account)return res.status(401).json({error:'Account not found'});next()}
async function hasRole(discordId){if(!REQUIRED_ROLE_ID||!DISCORD_BOT_TOKEN||!DISCORD_GUILD_ID)return false;const r=await fetch(`https://discord.com/api/v10/guilds/${DISCORD_GUILD_ID}/members/${discordId}`,{headers:{Authorization:`Bot ${DISCORD_BOT_TOKEN}`}});if(!r.ok)return false;const m=await r.json();return Array.isArray(m.roles)&&m.roles.includes(REQUIRED_ROLE_ID)}
function levelInfo(xp){let level=1,need=100;let left=xp;while(left>=need&&level<100){left-=need;level++;need=Math.floor(100*Math.pow(1.22,level-1))}return{level,nextLevelXp:need}}
function accountJSON(a,hasRequiredRole=false){const li=levelInfo(a.xp);return{growId:a.grow_id,discordLinked:!!a.discord_id,hasRequiredRole,balance:a.balance,xp:a.xp,level:li.level,nextLevelXp:li.nextLevelXp}}
function addXp(accountId,amount){const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(accountId);const li=levelInfo(a.xp+amount);db.prepare('UPDATE gamble_accounts SET xp=?,level=?,updated_at=? WHERE id=?').run(a.xp+amount,li.level,now(),accountId)}
function addHistory(accountId,game,label,wager,delta){db.prepare('INSERT INTO game_history(account_id,game,label,wager,delta,created_at) VALUES(?,?,?,?,?,?)').run(accountId,game,label,wager,delta,now())}
function debitCredit(accountId,delta){const a=db.prepare('SELECT balance FROM gamble_accounts WHERE id=?').get(accountId);if(!a)throw new Error('Account not found');const next=a.balance+delta;if(next<0)throw new Error('Insufficient credits');db.prepare('UPDATE gamble_accounts SET balance=?,updated_at=? WHERE id=?').run(next,now(),accountId)}
function requireRole(req,res,next){hasRole(req.account.discord_id).then(ok=>{if(!ok)return res.status(403).json({error:'Required Discord role is missing'});req.hasRole=true;next()}).catch(()=>res.status(503).json({error:'Discord verification unavailable'}))}

app.post('/api/gamble/link/complete',async(req,res)=>{const code=String(req.body.code||'');const row=db.prepare('SELECT * FROM link_codes WHERE code=? AND used_at IS NULL AND expires_at>?').get(code,now());if(!row)return res.status(400).json({error:'Invalid or expired link code'});const existing=db.prepare('SELECT * FROM gamble_accounts WHERE grow_id=? OR discord_id=?').get(row.grow_id,row.discord_id);if(existing && (existing.grow_id!==row.grow_id || existing.discord_id!==row.discord_id))return res.status(409).json({error:'GrowID or Discord is already linked to another Gamble account'});let account=existing;if(!account){const t=now();const r=db.prepare('INSERT INTO gamble_accounts(grow_id,discord_id,created_at,updated_at) VALUES(?,?,?,?)').run(row.grow_id,row.discord_id,t,t);account=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(r.lastInsertRowid)}db.prepare('UPDATE link_codes SET used_at=? WHERE code=?').run(now(),code);const sid=issueSession(account.id);res.setHeader('Set-Cookie',`${SESSION_COOKIE}=${sid}; Path=/; HttpOnly; SameSite=Lax; Secure`);res.json({account:accountJSON(account,await hasRole(account.discord_id))})});

app.get('/api/gamble/account',auth,async(req,res)=>res.json({account:accountJSON(req.account,await hasRole(req.account.discord_id))}));

app.post('/api/gamble/cases/open',auth,requireRole,(req,res)=>{
  const id=String(req.body.caseId||'');const cooldown={daily:86400,weekly:604800,monthly:2592000};
  const rewards={daily:[50,75,100,150,250],weekly:[250,400,600,900,1500],monthly:[1000,1500,2500,4000,7500],tier1:[25,50,75],tier2:[50,100,150,250],tier3:[100,200,350,500],tier4:[250,400,650,1000],tier5:[500,750,1200,2000]};
  if(!rewards[id])return res.status(400).json({error:'Unknown case'});const key='case:'+id;const cd=db.prepare('SELECT * FROM cooldowns WHERE account_id=? AND key=?').get(req.account.id,key);if(cd&&cd.available_at>now())return res.status(429).json({error:`Case available again in ${cd.available_at-now()} seconds`});
  const list=rewards[id];const reward=list[crypto.randomInt(list.length)];db.transaction(()=>{debitCredit(req.account.id,reward);if(cooldown[id])db.prepare('INSERT INTO cooldowns(account_id,key,available_at) VALUES(?,?,?) ON CONFLICT(account_id,key) DO UPDATE SET available_at=excluded.available_at').run(req.account.id,key,now()+cooldown[id]);addHistory(req.account.id,'case',id,0,reward);addXp(req.account.id,Math.min(50,Math.max(5,Math.floor(reward/10))))})();
  const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);res.json({reward,account:accountJSON(a,true)});
});

app.post('/api/gamble/play',auth,requireRole,(req,res)=>{
 const game=String(req.body.game||''),choice=String(req.body.choice||''),wager=Number(req.body.wager);if(!Number.isInteger(wager)||wager<1||wager>100000)return res.status(400).json({error:'Invalid wager'});const a=req.account;if(a.balance<wager)return res.status(400).json({error:'Insufficient credits'});
 let win=false,mult=0,message='';
 if(game==='coinflip'){const r=crypto.randomInt(2)?'heads':'tails';win=r===choice;mult=win?1.95:0;message=`Landed ${r}. ${win?'You win!':'You lose.'}`}
 else if(game==='dice'){const r=crypto.randomInt(1,101);win=choice==='low'?r<=49:r>=51;mult=win?1.95:0;message=`Rolled ${r}. ${win?'You win!':'You lose.'}`}
 else if(game==='roulette'){const n=crypto.randomInt(37);const result=n===0?'green':n%2?'red':'black';win=result===choice;mult=win?(result==='green'?14:1.95):0;message=`Wheel: ${result}. ${win?'You win!':'You lose.'}`}
 else if(game==='plinko'){const sets={low:[0,0,0.5,0.8,1,1,1.2,1.5,2],medium:[0,0.3,0.5,0.7,1,1,1.5,2.5,5],high:[0,0,0.2,0.5,1,1,2,5,12]};const arr=sets[choice]||sets.medium;mult=arr[crypto.randomInt(arr.length)];win=mult>0;message=`Ball landed on ${mult.toFixed(2)}×.`}
 else return res.status(400).json({error:'Unknown game'});
 const delta=Math.floor(wager*mult)-wager;db.transaction(()=>{debitCredit(a.id,delta);addXp(a.id,Math.min(100,Math.max(1,Math.floor(wager/25))));addHistory(a.id,game,game.toUpperCase(),wager,delta)})();const updated=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(a.id);res.json({message,delta,account:accountJSON(updated,true)});
});

app.post('/api/gamble/mines/start',auth,requireRole,(req,res)=>{const wager=Number(req.body.wager),mines=Number(req.body.mines);if(!Number.isInteger(wager)||wager<1||wager>100000)return res.status(400).json({error:'Invalid wager'});if(![3,5,7,10].includes(mines))return res.status(400).json({error:'Invalid mine count'});if(req.account.balance<wager)return res.status(400).json({error:'Insufficient credits'});const positions=new Set();while(positions.size<mines)positions.add(crypto.randomInt(25));const id=crypto.randomBytes(16).toString('hex');sessions.set('mines:'+id,{accountId:req.account.id,wager,mines,positions,opened:new Set(),created:Date.now()});debitCredit(req.account.id,-wager);const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);res.json({game:{id,tiles:Array(25).fill(0),opened:[],wager,mines},account:accountJSON(a,true)})});
function minesMultiplier(opened,mines){let m=1;for(let i=0;i<opened;i++)m*=((25-mines-(i))/(25-i));return 0.97/Math.max(m,0.0001)}
app.post('/api/gamble/mines/reveal',auth,requireRole,(req,res)=>{const id=String(req.body.gameId||'');const s=sessions.get('mines:'+id);if(!s||s.accountId!==req.account.id)return res.status(404).json({error:'Game not found'});const index=Number(req.body.index);if(!Number.isInteger(index)||index<0||index>=25)return res.status(400).json({error:'Invalid tile'});if(s.opened.has(index))return res.status(400).json({error:'Already opened'});s.opened.add(index);if(s.positions.has(index)){for(const p of s.positions)s.opened.add(p);sessions.delete('mines:'+id);addXp(req.account.id,Math.min(100,Math.floor(s.wager/25)));addHistory(req.account.id,'mines','MINES - mine',s.wager,-s.wager);const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);return res.json({mine:true,finished:true,mines:[...s.positions],message:'BOOM! You hit a mine.',account:accountJSON(a,true)})}const mult=minesMultiplier(s.opened.size,s.mines);const potential=Math.floor(s.wager*mult);const finished=s.opened.size===25-s.mines;if(finished){debitCredit(req.account.id,potential);sessions.delete('mines:'+id);addHistory(req.account.id,'mines','MINES - full clear',s.wager,potential);addXp(req.account.id,Math.min(100,Math.floor(s.wager/20)))}const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);res.json({mine:false,finished,mines:finished?[...s.positions]:[],message:finished?'Board cleared!':'Safe tile!',multiplier:mult,potential,game:{id,tiles:Array(25).fill(0),opened:[...s.opened],wager:s.wager,mines:s.mines},account:accountJSON(a,true)})});
app.post('/api/gamble/mines/cashout',auth,requireRole,(req,res)=>{const id=String(req.body.gameId||'');const s=sessions.get('mines:'+id);if(!s||s.accountId!==req.account.id)return res.status(404).json({error:'Game not found'});if(!s.opened.size)return res.status(400).json({error:'Reveal at least one tile'});const mult=minesMultiplier(s.opened.size,s.mines),payout=Math.floor(s.wager*mult),delta=payout;debitCredit(req.account.id,payout);sessions.delete('mines:'+id);addXp(req.account.id,Math.min(100,Math.floor(s.wager/20)));addHistory(req.account.id,'mines','MINES - cashout',s.wager,delta);const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);res.json({multiplier:mult,delta,account:accountJSON(a,true)})});

app.post('/api/gamble/crash/start',auth,requireRole,(req,res)=>{const wager=Number(req.body.wager);if(!Number.isInteger(wager)||wager<1||wager>100000)return res.status(400).json({error:'Invalid wager'});if(req.account.balance<wager)return res.status(400).json({error:'Insufficient credits'});const crashAt=1+(-Math.log(1-Math.random())/2.2);const id=crypto.randomBytes(16).toString('hex');sessions.set('crash:'+req.account.id,{id,wager,crashAt,started:Date.now(),accountId:req.account.id});debitCredit(req.account.id,-wager);const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);res.json({rate:0.75,gameId:id,account:accountJSON(a,true)})});
app.post('/api/gamble/crash/cashout',auth,requireRole,(req,res)=>{const s=sessions.get('crash:'+req.account.id);if(!s)return res.status(404).json({error:'No active crash round'});const elapsed=(Date.now()-s.started)/1000,mult=1+elapsed*0.75;if(mult>=s.crashAt){sessions.delete('crash:'+req.account.id);addHistory(req.account.id,'crash','CRASHED',s.wager,-s.wager);const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);return res.status(409).json({error:'Too late — the round crashed.'})}const payout=Math.floor(s.wager*mult);const delta=payout;debitCredit(req.account.id,payout);sessions.delete('crash:'+req.account.id);addXp(req.account.id,Math.min(100,Math.floor(s.wager/20)));addHistory(req.account.id,'crash','CRASH CASHOUT',s.wager,delta);const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);res.json({message:`Cashed out at ${mult.toFixed(2)}×`,delta,account:accountJSON(a,true)})});

app.post('/api/gamble/cashout',auth,async(req,res)=>{const amount=Number(req.body.amount);if(!Number.isInteger(amount)||amount<1)return res.status(400).json({error:'Invalid amount'});if(req.account.balance<amount)return res.status(400).json({error:'Insufficient credits'});const existing=db.prepare("SELECT id FROM cashouts WHERE account_id=? AND status='pending'").get(req.account.id);if(existing)return res.status(409).json({error:'You already have a pending cashout'});db.transaction(()=>{debitCredit(req.account.id,-amount);db.prepare("INSERT INTO cashouts(account_id,grow_id,amount,status,created_at) VALUES(?,?,?,'pending',?)").run(req.account.id,req.account.grow_id,amount,now());addHistory(req.account.id,'cashout','CASHOUT REQUEST',0,-amount)})();const a=db.prepare('SELECT * FROM gamble_accounts WHERE id=?').get(req.account.id);res.json({account:accountJSON(a,await hasRole(a.discord_id))})});
app.get('/api/gamble/history',auth,(req,res)=>res.json({items:db.prepare('SELECT label,delta FROM game_history WHERE account_id=? ORDER BY id DESC LIMIT 15').all(req.account.id)}));

// GTPS -> web bridge. These endpoints require the shared secret and are intended for the Lua script.
function bridge(req,res,next){const supplied=req.get('x-gtps-secret')||req.body?.secret||req.query?.secret;if(supplied!==GTPS_BRIDGE_SECRET)return res.status(401).json({error:'Unauthorized bridge'});next()}
app.post('/api/gamble/gtps/link-code',bridge,(req,res)=>{const growId=String(req.body.growId||'').trim(),discordId=String(req.body.discordId||'').trim();if(!growId||!discordId)return res.status(400).json({error:'growId and discordId required'});const code=String(crypto.randomInt(100000,1000000));db.prepare('INSERT INTO link_codes(code,grow_id,discord_id,expires_at) VALUES(?,?,?,?)').run(code,growId,discordId,now()+300);res.json({code,expiresIn:300})});
app.post('/api/gamble/gtps/deposit',bridge,(req,res)=>{const growId=String(req.body.growId||'').trim(),amount=Number(req.body.amount);if(!growId||!Number.isInteger(amount)||amount<1)return res.status(400).json({error:'Invalid deposit'});const a=db.prepare('SELECT * FROM gamble_accounts WHERE grow_id=?').get(growId);if(!a)return res.status(404).json({error:'Gamble account not linked'});debitCredit(a.id,amount);addHistory(a.id,'deposit','GTPS DEPOSIT',amount,amount);res.json({ok:true,balance:db.prepare('SELECT balance FROM gamble_accounts WHERE id=?').get(a.id).balance})});
app.get('/api/gamble/gtps/payouts',bridge,(req,res)=>{const growId=String(req.query.growId||'').trim();const p=db.prepare("SELECT * FROM cashouts WHERE grow_id=? AND status='pending' ORDER BY id ASC LIMIT 1").get(growId);res.json({payout:p||null})});
app.post('/api/gamble/gtps/payouts/complete',bridge,(req,res)=>{const id=Number(req.body.id);const p=db.prepare("SELECT * FROM cashouts WHERE id=? AND status='pending'").get(id);if(!p)return res.status(404).json({error:'Payout not found'});db.prepare("UPDATE cashouts SET status='paid',processed_at=? WHERE id=?").run(now(),id);res.json({ok:true})});

app.listen(PORT,()=>console.log(`Gamble API listening on ${PORT}`));
